### ISSUE TITLE
Enhancements on banner

### ISSUE THREAD

**Issue by ashrithr** [prydonius/spinning_cursor#19]
I was testing `spinning_cursor` and found out couple issues with way banner is printed out:
1. banner doesn't print instance variables
2. banner keeps on printing on the console if the banner's length is greater than 2 lines or something

Please take a look at the following code

``` ruby
require 'spinning_cursor'

@test = "some info"
@thread_count = 5
@threads = Array.new

def wait_time(times=10)
  @thread_count.times do |c|
    @threads << Thread.new { sleep 2; puts "thread #{c}"}
  end
  @threads.each { |t| t.join }
end

SpinningCursor.start do
  # banner does'nt take instance var's
  banner "Starting task #{@test}"
  message "Done"
  action do
    sleep 1
  end
end

SpinningCursor.start do
  # banner keeps on repeating, if string is more than 2 lines
  banner "Starting #{(0..400).map{ ('a'..'z').to_a[rand(26)] }.join}"
  message "Done"
  output :at_stop
end

wait_time

SpinningCursor.stop
```

I have tested this code in 1.9.3 and 1.8.7 both show same results.

**Comment by abinoam** [comment]
Hi ashrithr,

The block on 'start' is being instance_evaluated in another context.
So it will have the Parser instance instance variables available.
Not the upper context instance variables.

We began to discuss this issue some days ago.
We'll try to find out what would be a good behaviour for this.

Thank you for raising the issue.

**Comment by abinoam** [comment]
And, about the second point, we have to find a better way of handling it.
Perhaps saving the start point console position and getting into it before each update of the spinning cursor.

**Comment by ashrithr** [comment]
cool, that makes sense.

**Comment by prydonius** [comment]
Using instance variables for banners/messages can only be accomplished like this, I'm afraid:

``` ruby
SpinningCursor.start do
  message "Done"
  action do
    SpinningCursor.set_banner "Starting task #{@test}"
    sleep 1
  end
end
```

It's not pretty but it'll do what you want to do. As @abinoam says we have been discussing the evaluation of the action method, and perhaps some syntactic sugar may be introduced to remove the need of typing `SpinningCursor.method` inside the action block.

I have been working on the second issue, and will have a fix soon. However, I will need to test that it will work on Windows before releasing. Hopefully, I can do that this weekend.

**Comment by prydonius** [comment]
Fixed in f779279. Milestone set for 0.2.1 which hopefully will be released after a bit of fiddling with Windows (and me probably giving up any hope on this working on Windows :P). I'd appreciate it if you could checkout the master branch and see if this works as you'd expect, and if it doesn't feel free to reopen.

**Comment by ashrithr** [comment]
Hey I have checked out master and tested this over again but the banner overflowing still not fixed in 1.9.3, but works fine in 1.8.7 for some reason.

**Comment by prydonius** [comment]
Strange, I've just tested it on my machine and it's working for in 1.9.3. The tests also passed on Travis CI. Are you sure you're not requiring the rubygems version? Either uninstall it, or do something like this to the top of your file (assuming you put your script in the lib directory where you cloned this)
`$LOAD_PATH.unshift(File.dirname(__FILE__))`

**Comment by ashrithr** [comment]
Sorry about that, its works fine. Thanks for the update ... :+1:

**Comment by prydonius** [comment]
No worries :), glad it's working!

**Comment by abinoam** [comment]
@ashrithr if you really need to reference instance variables it will be possible after the last pull request get merged.
But, you will have to change a little bit your code.

Give a parameter to the block.
And call the methods (banner, action...etc) on that paramenter.

Like this.

``` ruby
@my_inst = "My Banner"
SpinningCursor.start do |sc|
  sc.banner @my_inst
  sc.action { sleep 2 }
end
```

**Comment by ashrithr** [comment]
Good to know. Thanx!
